// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csnltaeohbnccusomxee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzbmx0YWVvaGJuY2N1c29teGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTMyODYsImV4cCI6MjA2ODA2OTI4Nn0.kY3W2mCjL1_MGUb389wCxF7Uzak3xnTfc6I5NcqjZoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});